### ISSUE TITLE
Tendermint Node Crashes when specifying a `genesis.json` file

### ISSUE THREAD

**Issue by lidarwin** [keppel/lotion#130]
If we add the line `genesis: 'genesis.json'` into `example/counter/app.js` to get:

```javascript
let initialState = { count: 0, blockCount: 0, foo: { bar: { beep: 'boop' } } }

let port = 3000
let app = require('../../')({
  initialState,
  genesis: 'genesis.json',
  logTendermint: false,
  tendermintPort: 46657,
  p2pPort: 46661,
  devMode: true
})

app.use((state, tx) => {
  // validate tx, mutate state if it's valid.
  state.count++
})

app.useBlock(state => {
  state.blockCount++
})

app.listen(port).then(({ GCI }) => {
  console.log(GCI)
})
```

We get the error:
```
(node:1517) UnhandledPromiseRejectionWarning: Error: Timed out while waiting
    at /home/cosmicbridge/lotion/node_modules/tendermint-node/src/index.js:113:15
    at <anonymous>
(node:1517) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:1517) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Also note that doing 

```javascript
let initialState = { genesis:'genesis.json', count: 0, blockCount: 0, foo: { bar: { beep: 'boop' } } }
```
Does not crash, but is not using the `genesis.json` file as it generates a new GCI every time it runs.

**Comment by kiwec** [comment]
https://github.com/keppel/lotion/blob/develop/index.js#L37

Lotion expects a genesis.json to already exist when specified. The issue is more that there is no way to create/save a genesis and validator keys, as far as I am aware.

**Comment by nzoghb** [comment]
@keppel Was this ever resolved? Running into the exact same error. A genesis file exists and is specified, but getting 
```
(node:11175) UnhandledPromiseRejectionWarning: Error: Timed out while waiting
    at /Users/nick/node_modules/tendermint-node/src/index.js:119:15
    at <anonymous>
(node:11175) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:11175) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nzoghb** [comment]
@lidarwin figured out what my issue was, keep in mind that this is with `0.2.3`:

The error is thrown in the [tendermind-node](https://github.com/mappum/tendermint-node/blob/master/src/index.js#L132) repo, in my case I found out that it was due to a number of issues with my `genesis.json`. I recommend looking at the one [here](https://github.com/keppel/lotion/pull/155/files) for a correct implementation. Namely, for any `genesis.json`:

1. a validator's `power` must be a string
2. every value must be in double quotes
3. `app_hash` should be empty (unclear why but it was an error that came up)
4. `genesis_time` must end with a 'Z' and be in UTC

Setting `logTendermint` to `true` [helps with debugging](https://github.com/keppel/lotion/blob/develop/src/tendermint.ts#L117). A lot of these errors came about because of [how Amino decodes JSON values](https://github.com/tendermint/go-amino/blob/2106ca61d91029c931fd54968c2bb02dc96b1412/json-decode.go#L118)

Hope this helps!
