### ISSUE TITLE
Framework is not usable at all

### ISSUE THREAD

**Issue by axvm** [keppel/lotion#160]
Hi

This issue more for ppl who are trying to develop dapp using this framework. I spent few days to learn this framework and to check compatibility w/ latest tendermint abci specifications.

I'm not sure if this framework still in development but it completely uncompatible w/ last versions of tendermint abci interface. 
For example: [info](https://tendermint.com/docs/spec/abci/abci.html#info) method not implemented as it must to be. And because its doesnt returns required values in response, every blockchain app based on this framework will not sync w/ blockchain state after restart.
Framework documentation is outdated and examples are not working anymore.
The framework not just "unstable" or "under development". It is completely outdated and in my opinion maintainer need to mention it in readme.

No offence, lotion is a good start point to learn how abci works but it completely unusable at this moment.

**Comment by mappum** [comment]
You're correct that Lotion does not work with the latest versions of Tendermint, but that does not mean it is unusable.

We have kept Lotion compatible with Tendermint 0.26 and while we plan to upgrade to latest, it just has not yet been a priority. That's because the main benefit of the upgrade would be security and reliability fixes, while Lotion is currently not recommended for production apps securing real value. And the upgrade is much more than updating the ABCI code, but one very time-consuming part is upgrading the [Tendermint light client](https://github.com/mappum/js-tendermint), which has to be byte-for-byte compatible with many ever-changing Tendermint data structures.

That will definitely become our priority soon and we will upgrade all the infrastructure to the latest version of Tendermint, but just know that Lotion works just fine. Just on a slightly outdated version of Tendermint.

**Comment by keppel** [comment]
@axvm the persistence issue and the outdated docs have been fixed, thanks for opening this issue! :)

And like @mappum said, staying up-to-date with Tendermint is a non-goal for this project until Tendermint reaches version 1.0.
