### ISSUE TITLE
[Bug] Signing error

### ISSUE THREAD

**Issue by AlexMog** [keppel/lotion#71]
Hello,
When generating a new genesis & keys file by Lotion, everything works perfectly.
After copying the genesis & privkey file to the root of the Lotion project, and setting the genesis to be loaded from the genesis.json file and keys such as loaded by the privkey file, after setting to true the logs, I got this:
`E[01-21|17:28:18.153] Error signing vote                           module=consensus height=1 round=0 vote="Vote{0:12DCDF9D24F2 1/00/1(Prevote) 000000000000 {<nil>} @ 2018-01-21T17:28:18.153Z}" err="Error signing vote: Height regression"`

The height seems to be defined to 1 (see the log above), but it's 478 in my priv_validator.json

Is it a bug or am I doing it wrong?

Thanks for the help!

Best regards,
AlexMog.

**Comment by keppel** [comment]
hi Alex, thanks for the issue!

for now, if you delete everything except the values for `priv_key`, `pub_key`, and `address` from your `privkey.json`, I think it'll work. if that doesn't work, I'd `rm -rf ~/.lotion` and try again or run with `devMode: true`.

when running in validator mode, Tendermint keeps track of the height of the last block it signed. If your node hears about a block with a greater height than the last one it thinks it signed, Tendermint will halt instead of making new blocks since signing two blocks at the same height is against the rules and usually a punishable offense in proof-of-stake consensus protocols like Tendermint. so your `priv_validator.json` `last_height` field is being overwritten when you start the app, but you still have blocks you've already signed locally.
