### ISSUE TITLE
Chain Resets if i change the app Logic

### ISSUE THREAD

**Issue by santosh898** [keppel/lotion#78]
If i change the app logic on all the peers.And restart all the peers.The chain is starting from Block 0.
what's happening seems correct but,
Its bad if i have to start from the beginning.
Is there any solution for this?

**Comment by ameeuw** [comment]
Do you have you lotion app running in dev-mode?
If you have dev-mode enabled the lotionPath is randomly generated every time you start your app. This enables local testing but of as you pointed out resets the chain-data with every restart.

Here is the relevant code from the index.js:

```javascript
if (devMode) {
    lotionPath += Math.floor(Math.random() * 1e9)
    rimraf.sync(lotionPath)
    process.on('SIGINT', () => {
        rimraf.sync(lotionPath)
        process.exit()
    })
}
```

**Comment by santosh898** [comment]
1) Dev mode not enabled.
2) chain does not reset on every restart because of (1)
3) chain resets particularly when i change the app logic.
 And now i assume you got my point.

**Comment by ameeuw** [comment]
I am just trying to help. Maybe I still do not understand your problem but here is another go:

It seems obvious to me that a chain restart is necessary as soon as you change the app-logic because your state changes are dependent on your tx-handler.
If you change the way that transactions alter your state, your whole chain will look different and therefore has to be recomputed with the new logic. 

Think of it in the way of a new node joining the chain - it is trying to validate all of the state changes induced by transactions but cannot do this as it does not know how to validate the "earlier portion" of the existing chain.

I hope this helps - maybe you could post a brief snippet on how you are changing the logic then we can make sense whether this is actually a lotion issue.
