### ISSUE TITLE
docker support for lotion application

### ISSUE THREAD

**Issue by SaifRehman** [keppel/lotion#86]
The lotion port can not be accessed 
link : https://github.com/SaifRehman/tendermint-chat-app/blob/master/blockchain/Dockerfile
project: https://github.com/SaifRehman/tendermint-chat-app

**Comment by SaifRehman** [comment]
@keppel I cannot access lotion port inside a docker container, although i can access tendermint port running on 46657. please help, i want to run the app on a container and deploying it to IBM cloud 
link :  https://github.com/SaifRehman/tendermint-chat-app/blob/master/blockchain/Dockerfile
<img width="1280" alt="screen shot 2018-03-07 at 1 00 58 pm" src="https://user-images.githubusercontent.com/18755233/37083043-bc195918-2207-11e8-8ae7-f88d3994cdd4.png">

**Comment by keppel** [comment]
hey Saif!

the http api is just for talking to a full node running locally, so if you intend to run a node on the IBM cloud, I'd recommend using the [light client API](https://github.com/keppel/lotion#global-chain-identifiers-and-light-clients) which talks directly to your Tendermint node (which docker is correctly exposing for you), instead of the lotion http server.

**Comment by SaifRehman** [comment]
@keppel great, I got the concept now. This will work! Thanks. I will be writing a blog soon on medium to bring lotion app on IBM cloud. Is it possible it could be published on tendermint's medium or lotion. I just love to be part of this community

**Comment by SaifRehman** [comment]
got it, understood the whole concept clearly now
